### ISSUE TITLE
HOCON path references is NOT recognized  in string literals for java language

### ISSUE THREAD

**Issue by kool79** [AVSystem/intellij-hocon#21] opened 2019-10-15 14:49 UTC
> Version 2019.3.2: What’s New
>  * detection of HOCON path references in string literals of other languages

Actually HOCON path references is NOT recognized  in string literals for java language. 
![Screenshot - 15_10_2019 , 17_48_23](https://user-images.githubusercontent.com/4625317/66842506-0de70700-ef74-11e9-911f-ea9b869f0b94.png)

**Comment by kool79** [comment] 2019-10-15 14:57
'Find Usages' action on hocon entries (inside conf-file) also does not find usages inside Main.java file (see screenshot above)

**Comment by ghik** [comment] 2019-10-15 16:23
This one I can't reproduce (except for the problem with 'Find Usages' which is known). Can you provide your example project?

**Comment by ghik** [comment] 2019-10-22 10:59
@kool79 please check if the problem is still present in plugin version 2019.3.3

**Comment by kool79** [comment] 2019-10-22 12:52
Hi, @ghik 
 Issue still present in v2019.3.3
Project is very simple: Actually it has 2 files: src/Main.java and application.conf which is **located in project (module)  root**. 
   Sorry, I tried to attach my simple project to this post, but github shows error "something went really wrong .... ". Will try to attach later.

But I have more details to reproduce issue:
  When I move `application.conf` to `resource` directory AND mark this directory as 'Resources Root' in IDEA then everything works OK.  But when I move file back to project root it stopped to work again.  Also it stopped to work when I renamed `application.conf` to `app.conf` (inside `resource` directory)
   So plugin recognize only file named as `application.conf` and this file must be present in resources. 

   But in my case I use hocon  in non-standard scala project. In my project (actually it is functional tests written with testng and webdriver) I have several types of configurations (test-data, environment settings, browser configurations etc) and all those files are saved in custom location on disk (i.e. not inside jar-file/ resources).
   So I need that plugin recognize all conf files  in my project: with different names and  in different  locations.  Again:  Is it possible to implement? Maybe you can propose some workaround for my case ( fake application.conf etc)

**Comment by kool79** [comment] 2019-10-22 12:52
[simpleProject.zip](https://github.com/AVSystem/intellij-hocon/files/3755686/simpleProject.zip)

**Comment by ghik** [comment] 2019-10-22 13:08
@kool79 your description matches how it's implemented currently - references in string literals are looked up only in `application.conf` files in the root of the classpath. Again, this matches the most typical usage scenario for HOCON in Java/Scala projects. I will write more comprehensive documentation which will list details like this one.

In the meantime, the solution/workaround would be indeed to create a fake `application.conf` file in one of the sources/resource directories. This `application.conf` may then include everything that you want to be resolvable (you can use `file(...)` includes with paths relative to module root). In the long term it should probably be controlled by some configuration option. Resolving paths in all the visible HOCON files by default does not seem like a correct solution for me because this is never what actually happens in runtime. In general this is a tricky problem because HOCON files can be loaded in completely customized ways and the IntelliJ plugin has no idea about this.

**Comment by ghik** [comment] 2019-12-03 11:28
Closing this issue. If you think references should be looked up automatically in other files than `application.conf`, please create separate issue for that.

**Closed by ghik** 2019-12-03 11:28 UTC
